name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_isocalendar: yes
          plugin_languages : yes
          plugin_languages_ignored : >-
              c, cmake,
          plugin_languages_other : yes
          plugin_languages_details: bytes-size, percentage
          plugin_achievements: yes
          plugin_achievements_display: detailed
          config_order: base.header, isocalendar, languages, achievements
